Revert "scsi: ufs: Release clock if DMA map fails"
Got error:

../drivers/scsi/ufs/ufshcd.c:3227:21: error: too few arguments to function call, expected 2, have 1
                ufshcd_release(hba);
                ~~~~~~~~~~~~~~    ^
../drivers/scsi/ufs/ufshcd.c:1756:19: note: 'ufshcd_release' declared here
EXPORT_SYMBOL_GPL(ufshcd_release);
                  ^
../drivers/scsi/ufs/ufshcd.c:10132:44: error: shift count >= width of type [-Werror,-Wshift-count-overflow]
                if (!dma_set_mask_and_coherent(hba->dev, DMA_BIT_MASK(64)))
                                                         ^~~~~~~~~~~~~~~~
../include/linux/dma-mapping.h:173:54: note: expanded from macro 'DMA_BIT_MASK'
                                                     ^ ~~~

Here already declared ufshcd_release_all, not need add this too.

This reverts commit ffa5baf3150a3e4afcf5630a1715c39b1af2c619.